defaults:
  - model: UNet
  - metrics: AlignmentMetric
  - datasets: audio_dataset_eval   # we do not want to run inference on training data
  - dataloader: audio_dataset_eval
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["audio","notes"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "predict" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/UNet_hcqt/model_best.pth" # path to the pretrained model
