_target_: src.logger.WandBWriter
project_name: "Audio alignment model"
entity: null
run_name: "UNet_hcqt"
mode: "offline"
loss_names: ["train_loss","val_loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
